app/blueprints/view_auth.py
import datetime

from flask import Blueprint
from flask import redirect, url_for
from flask import render_template, request
from flask_login import login_required, current_user
from flask_login import login_user, logout_user

from ..utils.utils_auth import FlaskUser, UserRole, auth_utils
from ..utils.utils_error import render_error_template
from ..utils.utils_index import get_nav


bp_view_auth = Blueprint("view_auth", __name__)


# 登录
# http://127.0.0.1:5000/auth/login/
@bp_view_auth.route("/login/", methods=["GET", "POST"])
def login():

    # Template
    template_path = "auth_login.html"

    # Params
    params = {
        "nav":  get_nav(),
        "msgs": []
    }

    # GET
    if request.method == "GET":
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]

        # POST method=login
        if method == "login":
            auth_username = request.form.get("username").strip()
            auth_password = request.form.get("password").strip()

            result = auth_utils.login_account(
                auth_username=auth_username,
                auth_password=auth_password
            )
            params["msgs"].extend(result["msgs"])
            if result["msgs"][0]["type"] == "success":
                flask_user = FlaskUser(auth_user=result["auth_user"])
                login_user(flask_user)
                return redirect(url_for("view_index.index"))

            return render_template(template_path, **params)

    return render_error_template(message="系统错误")


# 注册
# http://127.0.0.1:5000/auth/signup/
@bp_view_auth.route("/signup/", methods=["GET", "POST"])
def signup():

    # Template
    template_path = "auth_signup.html"

    # Params
    params = {
        "nav":  get_nav(),
        "msgs": []
    }

    # GET /signup/
    if request.method == "GET":
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]

        # POST method=signup
        if method == "signup":
            auth_username   = request.form.get("username").strip()
            auth_password_1 = request.form.get("password_1").strip()
            auth_password_2 = request.form.get("password_2").strip()

            result = auth_utils.signup_account(
                auth_username=auth_username,
                auth_password_1=auth_password_1,
                auth_password_2=auth_password_2
            )
            params["msgs"].extend(result["msgs"])
            if result["msgs"][0]["type"] == "success":
                flask_user = FlaskUser(auth_user=result["auth_user"])
                login_user(flask_user)
                return redirect(url_for("view_index.index"))

            return render_template(template_path, **params)

    return render_error_template(message="系统错误")


# 账户
# http://127.0.0.1:5000/auth/account/
@bp_view_auth.route("/account/", methods=["GET", "POST"])
@login_required
def account():

    # Verify
    if current_user.role not in auth_utils.field_role_options:
        return render_error_template(message="您没有权限访问")

    # Template
    template_path = "auth_account.html"

    # Params
    params = {
        "nav": get_nav(),
        "msgs": [],
        "config": {
            "auth_headers": auth_utils.field_headers
        }
    }

    # GET
    if request.method == "GET":
        print("[INFO] %s %s/%s (%s) [%s] => %s" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role,
            request.method, request.endpoint
        ))
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]
        print("[INFO] %s %s/%s (%s) [%s] => %s [method=%s]" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role, 
            request.method, request.endpoint, method
        ))

        # POST method=update
        if method == "update":
            auth_idno           = request.form["idno"]
            auth_username_new   = request.form["username_new"]
            auth_password_new_1 = request.form["password_new_1"]
            auth_password_new_2 = request.form["password_new_2"]

            if auth_username_new or auth_password_new_1 or auth_password_new_2:
                result = auth_utils.update_account(
                    auth_idno=auth_idno,
                    auth_username_new=auth_username_new,
                    auth_password_new_1=auth_password_new_1,
                    auth_password_new_2=auth_password_new_2
                )
                params["msgs"].extend(result["msgs"])
                logout_user()
                flask_user = FlaskUser(auth_user=result["auth_user"])
                login_user(flask_user)

            return render_template(template_path, **params)

    return render_error_template(message="系统错误")


# 登出
# http://127.0.0.1:5000/auth/logout/
@bp_view_auth.route("/logout/", methods=["GET"])
@login_required
def logout():

    # Verify
    if current_user.role not in auth_utils.field_role_options:
        return render_error_template(message="您没有权限访问")

    # GET
    if request.method == "GET":
        logout_user()
        return redirect(url_for("view_index.index"))

    return render_error_template(message="系统错误")


# 管理权限
# http://127.0.0.1:5000/auth/role/
@bp_view_auth.route("/role/", methods=["GET", "POST"])
@login_required
def role():

    # Verify
    if current_user.role not in [UserRole.admin]:
        return render_error_template(message="您没有权限访问")

    # Template
    template_path = "auth_role.html"

    # Params
    params = {
        "nav": get_nav(),
        "msgs": [],
        "config": {
            "auth_role_options": auth_utils.field_role_options,
            "auth_role_headers": auth_utils.field_role_headers
        },
        "auth_role_infos": {},
    }

    # GET
    if request.method == "GET":
        print("[INFO] %s %s/%s (%s) [%s] => %s" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role,
            request.method, request.endpoint
        ))
        params["auth_role_infos"] = auth_utils.get_role_infos()
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]
        print("[INFO] %s %s/%s (%s) [%s] => %s [method=%s]" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role, 
            request.method, request.endpoint, method
        ))

        # POST method=update
        if method == "update":
            auth_idno     = request.form["auth_idno"]
            auth_role_new = request.form["auth_role_new"]

            if auth_idno or auth_role_new:
                result = auth_utils.update_role(
                    auth_idno=auth_idno, 
                    auth_role_new=auth_role_new
                )
                params["msgs"].extend(result["msgs"])

            params["auth_role_infos"] = auth_utils.get_role_infos()
            return render_template(template_path, **params)

    return render_error_template(message="系统错误")

app/blueprints/view_tool.py
import datetime
import os

from flask import Blueprint
from flask import render_template, request
from flask import send_file, send_from_directory
from flask_login import login_required, current_user

from ..utils.utils_auth import UserRole
from ..utils.utils_error import render_error_template
from ..utils.utils_file import file_utils
from ..utils.utils_index import get_nav
from ..utils.utils_tool_dakaji import search_dakaji, preprocess_dakaji
from ..utils.utils_tool_tencent import preprocess_tencent
from ..utils.utils_tool_wenjuanxing_1 import preprocess_wenjuanxing_1
from ..utils.utils_tool_wenjuanxing_2 import preprocess_wenjuanxing_2
from ..utils.utils_tool_zoom import preprocess_zoom


bp_view_tool = Blueprint("view_tool", __name__)


# 文件
# http://127.0.0.1:5000/tool/file/
@bp_view_tool.route("/file/", methods=["GET", "POST"])
def file():

    # GET
    if request.method == "GET":
        method    = request.args["method"]
        file_dir  = request.args["file_dir"]
        file_name = request.args["file_name"]
        save_name = request.args.get("save_name", file_name)

        # GET method=send_from_directory
        if method == "send_from_directory":
            return send_from_directory(directory=file_dir, path=file_name)

        # GET method=send_file
        if method == "send_file":
            file_path = file_utils.get_path(file_dir, file_name)
            if os.path.isfile(file_path):
                return send_file(file_path, download_name=save_name)
            else:
                return render_error_template(message="文件不存在 [ file_dir=%s, file_name=%s ]" % (file_dir, file_name))

    # POST
    if request.method == "POST":
        method    = request.form["method"]
        file_dir  = request.form["file_dir"]
        file_name = request.form["file_name"]
        save_name = request.form.get("save_name", file_name)

        # POST method=send_from_directory
        if method == "send_from_directory":
            return send_from_directory(directory=file_dir, path=file_name)

        # POST method=send_file
        if method == "send_file":
            file_path = file_utils.get_path(file_dir, file_name)
            if os.path.isfile(file_path):
                return send_file(file_path, download_name=save_name)
            else:
                return render_error_template(message="文件不存在 [ file_dir=%s, file_name=%s ]" % (file_dir, file_name))


# 问卷星
# http://127.0.0.1:5000/tool/wenjuanxing/
@bp_view_tool.route("/wenjuanxing/", methods=["GET", "POST"])
@login_required
def wenjuanxing():

    # Verify
    if current_user.role not in [UserRole.admin]:
        return render_error_template(message="您没有权限访问")

    # Template
    template_path = "tool_wenjuanxing.html"

    # Params
    params = {
        "nav": get_nav(),
        "msgs": [],
        "config": {
            "upload": {
                "upload_wenjuanxing_1": {
                    "file_name":   "upload_file_1",
                    "placeholder": "问卷星 报名表 (格式 1).xlsx",
                    "image":       "tool_utils-wenjuanxing-unprocessed-1.png",
                },
                "upload_wenjuanxing_2": {
                    "file_name":   "upload_file_2",
                    "placeholder": "问卷星 报名表 (格式 2).xlsx",
                    "image":       "tool_utils-wenjuanxing-unprocessed-2.png",
                },
            },
        },
        "file_infos": None,
    }

    # GET
    if request.method == "GET":
        print("[INFO] %s %s/%s (%s) [%s] => %s" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role,
            request.method, request.endpoint
        ))
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]
        print("[INFO] %s %s/%s (%s) [%s] => %s [method=%s]" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role, 
            request.method, request.endpoint, method
        ))

        # POST method=upload_wenjuanxing_1 or method=upload_wenjuanxing_2
        if method in ["upload_wenjuanxing_1", "upload_wenjuanxing_2"]:
            preprocess_wenjuanxings = {
                "upload_wenjuanxing_1": preprocess_wenjuanxing_1,
                "upload_wenjuanxing_2": preprocess_wenjuanxing_2,
            }
            file_name = params["config"]["upload"][method]["file_name"]
            preprocess_wenjuanxing = preprocess_wenjuanxings[method]
            upload_file = request.files[file_name]
            if upload_file:
                # 保存文件
                date_info = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                file_dir = "temp_dir"
                file_name = "tool_utils-wenjuanxing-%s.xlsx" % date_info
                save_name = "问卷星-%s.xlsx" % date_info
                upload_path   = "%s/%s" % (file_utils.temp_dir, file_name.replace(".xlsx", "-unprocessed.xlsx"))
                download_path = "%s/%s" % (file_utils.temp_dir, file_name)
                upload_file.save(upload_path)
                # 处理文件
                result = preprocess_wenjuanxing(upload_path, download_path)
                params["msgs"].extend(result["msgs"])
                if params["msgs"][-1]["type"] == "success":
                    params["file_infos"] = [{"file_dir": file_dir, "file_name": file_name, "save_name": save_name}]
            return render_template(template_path, **params)

    return render_error_template(message="系统错误")


# Zoom
# http://127.0.0.1:5000/tool/zoom/
@bp_view_tool.route("/zoom/", methods=["GET", "POST"])
@login_required
def zoom():

    # Verify
    if current_user.role not in [UserRole.admin]:
        return render_error_template(message="您没有权限访问")

    # Template
    template_path = "tool_zoom.html"

    # Params
    params = {
        "nav": get_nav(),
        "msgs": [],
        "config": {
            "upload": {
                "upload_zoom": {
                    "file_name":   "upload_file",
                    "placeholder": "Zoom 签到表.xlsx",
                    "image":       "tool_utils-zoom-unprocessed.png",
                },
            }
        },
        "file_infos": None,
    }

    # GET
    if request.method == "GET":
        print("[INFO] %s %s/%s (%s) [%s] => %s" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role,
            request.method, request.endpoint
        ))
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]
        print("[INFO] %s %s/%s (%s) [%s] => %s [method=%s]" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role, 
            request.method, request.endpoint, method
        ))

        # POST method=upload_zoom
        if method == "upload_zoom":
            file_name = params["config"]["upload"][method]["file_name"]
            upload_file = request.files[file_name]
            if upload_file:
                # 保存文件
                date_info = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                file_dir = "temp_dir"
                file_name = "tool_utils-zoom-%s.xlsx" % date_info
                save_name = "Zoom-%s.xlsx" % date_info
                upload_path   = "%s/%s" % (file_utils.temp_dir, file_name.replace(".xlsx", "-unprocessed.xlsx"))
                download_path = "%s/%s" % (file_utils.temp_dir, file_name)
                upload_file.save(upload_path)
                # 处理文件
                result = preprocess_zoom(upload_path, download_path)
                params["msgs"].extend(result["msgs"])
                if params["msgs"][-1]["type"] == "success":
                    params["file_infos"] = [{"file_dir": file_dir, "file_name": file_name, "save_name": save_name}]
            return render_template(template_path, **params)

    return render_error_template(message="系统错误")


# 腾讯会议
# http://127.0.0.1:5000/tool/tencent/
@bp_view_tool.route("/tencent/", methods=["GET", "POST"])
@login_required
def tencent():

    # Verify
    if current_user.role not in [UserRole.admin]:
        return render_error_template(message="您没有权限访问")

    # Template
    template_path = "tool_tencent.html"

    # Params
    params = {
        "nav": get_nav(),
        "msgs": [],
        "config": {
            "upload": {
                "upload_tencent": {
                    "file_name":   "upload_file",
                    "placeholder": "腾讯会议 签到表.xlsx",
                    "image":       "tool_utils-tencent-unprocessed.png",
                },
            }
        },
        "file_infos": None,
    }

    # GET
    if request.method == "GET":
        print("[INFO] %s %s/%s (%s) [%s] => %s" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role,
            request.method, request.endpoint
        ))
        return render_template(template_path, **params)

    # POST
    if request.method == "POST":
        method = request.form["method"]
        print("[INFO] %s %s/%s (%s) [%s] => %s [method=%s]" % (
            datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            current_user.idno, current_user.username, current_user.role, 
            request.method, request.endpoint, method
        ))

        # POST method=upload_tencent
        if method == "upload_tencent":
            file_name = params["config"]["upload"][method]["file_name"]
            upload_file = request.files[file_name]
            if upload_file:
                # 保存文件
                date_info = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                file_dir = "temp_dir"

app/templates/auth_account.html
{% extends "base.html" %}

{% block content %}
<div class="block">

    <!-- 标题 -->
    <div class="box-invis">
        <div class="content">
            <a href="{{ url_for("view_auth.account") }}">
                <h1>账户</h1>
            </a>
        </div>
    </div>

    <!-- 消息 -->
    {% if msgs %}
        {% for __msg in msgs %}
            <div class="box-invis">
                {% if __msg["type"] == "success" %}
                    <div class="notification is-success"    style="width: 40rem">
                {% elif __msg["type"] == "info" %}
                    <div class="notification is-info"       style="width: 40rem">
                {% elif __msg["type"] == "warn" %}
                    <div class="notification is-warning"    style="width: 40rem">
                {% elif __msg["type"] == "error" %}
                    <div class="notification is-danger"     style="width: 40rem">
                {% endif %}
                        <button class="delete"></button>
                        {{ __msg["text"]|safe }}
                    </div>
            </div>
        {% endfor %}
    {% endif %}

    <!-- 账户 -->
    <div class="box">

        <!-- 表单 -->
        <div class="box-invis">
            <form action="{{ url_for("view_auth.account") }}" method="POST">
                <table class="table is-hoverable">
                    <!-- 隐藏字段 -->
                    <input name="idno" value="{{ current_user.idno }}" hidden>

                    <tbody>
                        <!-- 固定字段 -->
                        <tr>
                            <th style="text-align: center; width: 10rem">{{ config["auth_headers"]["idno"] }}</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.idno }}</td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 10rem">{{ config["auth_headers"]["role"] }}</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.role }}</td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 10rem">{{ config["auth_headers"]["username"] }}</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.username }}</td>
                        </tr>
                        <!-- 可变字段 -->
                        <tr>
                            <th style="text-align: center; width: 10rem">[修改] {{ config["auth_headers"]["username"] }}</th>
                            <td style="text-align: center; width: 25rem">
                                <input class="table-input" type="text" style="text-align: center; width: 25rem"
                                name="username_new" placeholder="请输入 新账号">
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 10rem" rowspan="2">[修改] {{ config["auth_headers"]["password"] }}</th>
                            <td style="text-align: center; width: 25rem">
                                <input class="table-input" type="password" style="text-align: center; width: 25rem"
                                name="password_new_1" placeholder="请输入 新密码">
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center; width: 25rem">
                                <input class="table-input" type="password" style="text-align: center; width: 25rem"
                                name="password_new_2" placeholder="请再次输入 新密码">
                            </td>
                        </tr>
                        <!-- 固定字段 -->
                        <tr>
                            <th style="text-align: center; width: 10rem">创建时间</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.createtime|strftime }}</td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 10rem">修改时间</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.modifytime|strftime }}</td>
                        </tr>
                        <tr>
                            <th style="text-align: center; width: 10rem">修改用户</th>
                            <td style="text-align: center; width: 25rem; font-weight: bold">{{ current_user.modifyuser }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="field has-addons">
                    <div class="control"><button class="button" type="submit" name="method" value="update">更新</button></div>
                    <div class="control"><button class="button" type="reset">重置</button></div>
                </div>
            <form>
        </div>
    </div>

</div>
{% endblock %}

{% block script %}
<script>
// 关闭消息
document.addEventListener("DOMContentLoaded", () => {
    (document.querySelectorAll(".notification .delete") || []).forEach(($delete) => {
        const $notification = $delete.parentNode.parentNode;
        $delete.addEventListener("click", () => {
            $notification.parentNode.removeChild($notification);
        });
    });
});
</script>
{% endblock %}

app/templates/auth_login.html
{% extends "base.html" %}

{% block content %}
<div class="block">

    <!-- 标题 -->
    <div class="box-invis">
        <div class="content">
            <a href="{{ url_for("view_auth.login") }}">
                <h1>登录</h1>
            </a>
        </div>
    </div>

    <!-- 消息 -->
    {% if msgs %}
        {% for __msg in msgs %}
            <div class="box-invis">
                {% if __msg["type"] == "success" %}
                    <div class="notification is-success"    style="width: 40rem">
                {% elif __msg["type"] == "info" %}
                    <div class="notification is-info"       style="width: 40rem">
                {% elif __msg["type"] == "warn" %}
                    <div class="notification is-warning"    style="width: 40rem">
                {% elif __msg["type"] == "error" %}
                    <div class="notification is-danger"     style="width: 40rem">
                {% endif %}
                        <button class="delete"></button>
                        {{ __msg["text"]|safe }}
                    </div>
            </div>
        {% endfor %}
    {% endif %}

    <!-- 登录 -->
    <div class="box">

        <!-- 表单 -->
        <div class="box-invis">
            <form action="{{ url_for("view_auth.login") }}"" method="POST" >
                <div class="field has-addons" style="width: 20rem">
                    <div class="control"><input class="input" style="width: 20rem" type="text"     name="username" placeholder="请输入 用户名" autofocus></div>
                </div>
                <div class="field has-addons" style="width: 20rem">
                    <div class="control"><input class="input" style="width: 20rem" type="password" name="password" placeholder="请输入 密码"></div>
                </div>
                <div class="field has-addons" style="width: 20rem">
                    <div class="control"><button class="button is-primary" style="width: 10rem" type="submit" name="method" value="login">登录</button></div>
                    <div class="control"><button class="button is-light"   style="width: 10rem" type="reset">重置</button></div>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

{% block script %}
<script>
// 关闭消息
document.addEventListener("DOMContentLoaded", () => {
    (document.querySelectorAll(".notification .delete") || []).forEach(($delete) => {
        const $notification = $delete.parentNode.parentNode;
        $delete.addEventListener("click", () => {
            $notification.parentNode.removeChild($notification);
        });
    });
});
</script>
{% endblock %}

app/templates/tool_zoom.html
{% extends "base.html" %}

{% block content %}
<div class="block">

    <!-- 标题 -->
    <div class="box-invis">
        <div class="content">
            <a href="{{ url_for("view_tool.zoom") }}">
                <h1>Zoom</h1>
            </a>
        </div>
    </div>

    <!-- 消息 -->
    {% if msgs %}
        {% for __msg in msgs %}
            <div class="box-invis">
                {% if __msg["type"] == "success" %}
                    <div class="notification is-success"    style="width: 40rem">
                {% elif __msg["type"] == "info" %}
                    <div class="notification is-info"       style="width: 40rem">
                {% elif __msg["type"] == "warn" %}
                    <div class="notification is-warning"    style="width: 40rem">
                {% elif __msg["type"] == "error" %}
                    <div class="notification is-danger"     style="width: 40rem">
                {% endif %}
                        <button class="delete"></button>
                        {{ __msg["text"]|safe }}
                    </div>
            </div>
        {% endfor %}
    {% endif %}

    <!-- 上传文件 -->
    <div class="box">

        <div class="box-invis">
            <div class="content">
                <h2>上传数据</h2>
            </div>
        </div>

        {% for __method, __config in config["upload"].items() %}
            {% set __file_name   = __config["file_name"] %}
            {% set __placeholder = __config["placeholder"] %}
            {% set __image       = __config["image"] %}
            {% set __reset_value = "reset_"+loop.index|string %}
            {% set __upload_id   = "id_upload_file_"+loop.index|string %}

            <div class="box-invis">
                <img
                    src="/static/image/{{ __image }}"
                    style="display: block; margin-left: auto; margin-right: auto; object-fit: contain; height: 5rem""
                >
            </div>

            <div class="box-invis">
                <form action="{{ url_for("view_tool.zoom") }}" method="POST" enctype="multipart/form-data">
                    <div class="field has-addons">
                        <div class="file has-name" id="{{ __upload_id }}">
                            <label class="file-label">
                                <input class="file-input" type="file" name="{{ __file_name }}" accept=".xlsx">
                                <span class="file-cta"  style="width: 5rem">
                                    上传
                                </span>
                                <span class="file-name" style="width: 20rem; max-width: 20rem; opacity: 0.5">
                                    {{ __placeholder }}
                                </span>
                            </label>
                        </div>
                    </div>
                    <div class="field has-addons">
                        <div class="control"><button class="button is-base" style="width: 5rem" type="submit" name="method" value="{{ __method }}"      >提交</button></div>
                        <div class="control"><button class="button"         style="width: 5rem" type="reset"  name="reset"  value="{{ __reset_value }}" >重置</button></div>
                    </div>
                </form>
            </div>
        {% endfor %}

    </div>

    <!-- 下载数据 -->
    {% if file_infos is not none %}
        <div class="box">

            <div class="box-invis">
                <div class="content">
                    <h2>下载数据</h2>
                </div>
            </div>

            <div class="box-invis">
                {% for __file_info in file_infos %}
                    <form action="{{ url_for("view_tool.file") }}" method="POST">
                        <input name="file_dir"  value="{{ __file_info["file_dir"]  }}" hidden>
                        <input name="file_name" value="{{ __file_info["file_name"] }}" hidden>
                        <input name="save_name" value="{{ __file_info["save_name"] }}" hidden>
                        <div class="field has-addons">
                            <button class="button is-base" name="method" value="send_file">{{ __file_info["save_name"] }}</button>
                        </div>
                    </form>
                {% endfor %}
            </div>

        </div>
    {% endif %}

</div>
{% endblock %}

{% block script %}
<script>
// 关闭消息
document.addEventListener("DOMContentLoaded", () => {
    (document.querySelectorAll(".notification .delete") || []).forEach(($delete) => {
        const $notification = $delete.parentNode.parentNode;
        $delete.addEventListener("click", () => {
            $notification.parentNode.removeChild($notification);
        });
    });
});

{% for __method, __config in config["upload"].items() %}
    {% set __placeholder  = __config["placeholder"] %}
    {% set __upload_file  = "uploadFile"+loop.index|string %}
    {% set __upload_id    = "id_upload_file_"+loop.index|string %}
    {% set __upload_name  = "uploadFileName"+loop.index|string %}
    {% set __reset_button = "resetButton"+loop.index|string %}
    {% set __reset_value  = "reset_"+loop.index|string %}
    // 上传文件后，显示文件名
    const {{ __upload_file }} = document.querySelector("#{{ __upload_id }} input[type=file]");
    {{ __upload_file }}.onchange = () => {
        if ({{ __upload_file }}.files.length > 0) {
            // 显示上传文件名
            const {{ __upload_name }} = document.querySelector("#{{ __upload_id }} .file-name");
            {{ __upload_name }}.textContent = {{ __upload_file }}.files[0].name;
            {{ __upload_name }}.style.opacity = 1;
        }
    }

    // 重置文件后，还原文件名
    const {{ __reset_button }} = document.querySelector("form button[value={{ __reset_value }}]");
    {{ __reset_button }}.onclick = () => {
        // 重置上传文件名
        const uploadFileName1 = document.querySelector("#{{ __upload_id }} .file-name");
        uploadFileName1.textContent = "{{ __placeholder }}";
        uploadFileName1.style.opacity = 0.5;
    }
{% endfor %}
</script>
{% endblock %}